<a href="https://colab.research.google.com/github/DevAnand-debugger/project/blob/main/edaa1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name=Dev Anand

PRN=25070123039

Batch=A2

Experiment-9

Operations on Dataset

Create Dataset and Dataloading

In [53]:
#Dataset creation
import pandas as pd
data = {
    "Roll_No":[101,102,103,104,105],
    "Gender":["Female","Male","Female","Male","Female"],
    "Department":["Computer","IT","ENTC","Mechanical","Computer"],
    "CGPA":[8.2,7.5,9.1,6.8,8.7]
}

df = pd.DataFrame(data)

df.to_csv("students.csv",index=False)#this false indexing removes indexing from downloaded exv=cael file
df

   Roll_No  Gender  Department  CGPA
0      101  Female    Computer   8.2
1      102    Male          IT   7.5
2      103  Female        ENTC   9.1
3      104    Male  Mechanical   6.8
4      105  Female    Computer   8.7

In [4]:
df["year"]=["First","Second","First","Second","First"]
df.to_csv("students.csv",index=False)
df

   Roll_No  Gender  Department  CGPA    year
0      101  Female    Computer   8.2   First
1      102    Male          IT   7.5  Second
2      103  Female        ENTC   9.1   First
3      104    Male  Mechanical   6.8  Second
4      105  Female    Computer   8.7   First

In [6]:
df.shape

(5, 5)

In [7]:
df.size

25

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
 4   year        5 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [11]:
df.describe()

          Roll_No     CGPA
count    5.000000  5.00000
mean   103.000000  8.06000
std      1.581139  0.92358
min    101.000000  6.80000
25%    102.000000  7.50000
50%    103.000000  8.20000
75%    104.000000  8.70000
max    105.000000  9.10000

In [12]:
#Access information of column department
df["Department"]

0      Computer
1            IT
2          ENTC
3    Mechanical
4      Computer
Name: Department, dtype: object

In [15]:
#Access information of prn 103
df.loc[2]

Roll_No          103
Gender        Female
Department      ENTC
CGPA             9.1
year           First
Name: 2, dtype: object

In [19]:
#data type of each column
df.dtypes

Roll_No         int64
Gender         object
Department     object
CGPA          float64
year           object
dtype: object

In [25]:
#Perform mean,median,mode operation
mean1=df["CGPA"].mean()
mean1

np.float64(8.059999999999999)

In [26]:
#Find Median
median1=df["Roll_No"].median()
median1

103.0

In [28]:
#mode
mode1=df["CGPA"].mode()
mode1

0    6.8
1    7.5
2    8.2
3    8.7
4    9.1
Name: CGPA, dtype: float64

In [31]:
#new Grade Column
df["Grade"]=["A","B","A","C","D"]
df

   Roll_No  Gender  Department  CGPA    year Grade
0      101  Female    Computer   8.2   First     A
1      102    Male          IT   7.5  Second     B
2      103  Female        ENTC   9.1   First     A
3      104    Male  Mechanical   6.8  Second     C
4      105  Female    Computer   8.7   First     D

In [54]:
df.drop("Gender",axis=1,inplace=True)
df

   Roll_No  Department  CGPA
0      101    Computer   8.2
1      102          IT   7.5
2      103        ENTC   9.1
3      104  Mechanical   6.8
4      105    Computer   8.7

In [32]:
# CGPA of topper
df["CGPA"].max()

9.1

In [55]:
# CGPA of PRN 105
df[df["Roll_No"]==105]["CGPA"]

4    8.7
Name: CGPA, dtype: float64

In [43]:
#Upload the Dataset
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Cars93.csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [46]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [45]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [49]:
df.size

930

In [50]:
df.shape

(93, 10)

In [51]:
df.dtypes

Manufacturer       object
Model              object
Type               object
Price             float64
MPG.city            int64
AirBags            object
Horsepower          int64
Passengers          int64
Rear.seat.room    float64
Luggage.room      float64
dtype: object

In [56]:
df=pd.read_csv("/content/edab.csv")
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,24-11-2023,CUST001,Male,34,Beauty,3,50,150
1,2,27-02-2023,CUST002,Female,26,Clothing,2,500,1000
2,3,13-01-2023,CUST003,Male,50,Electronics,1,30,30
3,4,21-05-2023,CUST004,Male,37,Clothing,1,500,500
4,5,06-05-2023,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,16-05-2023,CUST996,Male,62,Clothing,1,50,50
996,997,17-11-2023,CUST997,Male,52,Beauty,3,30,90
997,998,29-10-2023,CUST998,Female,23,Beauty,4,25,100
998,999,05-12-2023,CUST999,Female,36,Electronics,3,50,150
999,1000,12-04-2023,CUST1000,Male,47,Electronics,4,30,120

In [57]:
df.shape

(1000, 9)

In [58]:
df.size

9000

In [60]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,24-11-2023,CUST001,Male,34,Beauty,3,50,150
1,2,27-02-2023,CUST002,Female,26,Clothing,2,500,1000
2,3,13-01-2023,CUST003,Male,50,Electronics,1,30,30
3,4,21-05-2023,CUST004,Male,37,Clothing,1,500,500
4,5,06-05-2023,CUST005,Male,30,Beauty,2,50,100

In [61]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,16-05-2023,CUST996,Male,62,Clothing,1,50,50
996,997,17-11-2023,CUST997,Male,52,Beauty,3,30,90
997,998,29-10-2023,CUST998,Female,23,Beauty,4,25,100
998,999,05-12-2023,CUST999,Female,36,Electronics,3,50,150
999,1000,12-04-2023,CUST1000,Male,47,Electronics,4,30,120

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB